version: '3'
services:
  sut:
    environment:
      TSAPIKEY: "$TSAPIKEY"
      TSKEY: "$TSKEY"
    build: .
    network_mode: host
    command: run_tests.sh
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    mem_limit: 5.6gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 41641/udp
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_ADMIN
