services:
  sut:
    environment:
      - TSAPIKEY
      - TSKEY
    build: .
    network_mode: host
    command: run_tests.sh
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    shm_size: 5.6gb
    shm_size: 5.6gb
  ulimits:
    memlock:
      soft: -1
      hard: -1
  ports:
      - "41641:41641/udp"
  cap_add:
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_ADMIN