services:
  sut:
    environment:
      - TSAPIKEY
      - TSKEY
    build: .
    network_mode: host
    command: run_tests.sh
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket