#!/bin/bash

VERSION=2.1.14
OS=linux  # or "darwin" for OSX, "windows" for Windows.
ARCH=amd64  # or "386" for 32-bit OSs

curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" \
| tar xz docker-credential-gcr \
&& chmod +x docker-credential-gcr && sudo mv docker-credential-gcr /usr/bin/

docker-credential-gcr configure-docker --registries=us-west4-docker.pkg.dev,us-docker.pkg.dev

export NUMEXPR_MAX_THREADS='$(nproc)'
#used by conda to specify cpus for building packages
export MAKEFLAGS='-j$(nproc)'
#used by conda
export CPU_COUNT='$(nproc)'

export IMAGETYPE=$DOCKER_TAG
docker buildx create --use --driver=docker-container --name container

# Set image type based on build argument
docker buildx build \
--push \
-t jcoffi/cluster-anywhere:$DOCKER_TAG \
--ulimit 'memlock=-1' \
--cache-to type=s3,region=us-west-2,bucket=cluster-anywhere,name=cluster-anywhere-$DOCKER_TAG \
--cache-from type=s3,region=us-west-2,bucket=cluster-anywhere,name=cluster-anywhere-$DOCKER_TAG \
--cache-to type=registry,ref=us-docker.pkg.dev/cluster-anywhere/cluster-anywhere:$DOCKER_TAG \
--build-arg IMAGETYPE=$DOCKER_TAG .
##--ulimit 'nofile=65535:65535' \
##--cache-from=rayproject/ray:latest-py310-$DOCKER_TAG \
##--cache-to type=registry,ref=jcoffi/ray:latest-py310-$DOCKER_TAG-cache \
##--cache-from type=registry,ref=jcoffi/ray:latest-py310-$DOCKER_TAG-cache \
##--cache-to type=s3,region=us-west-2,bucket=cluster-anywhere,name=latest-py310-$DOCKER_TAG-cache \
##--cache-from type=s3,region=us-west-2,bucket=cluster-anywhere,name=latest-py310-$DOCKER_TAG-cache \
