#!/bin/bash
export NUMEXPR_MAX_THREADS='$(nproc)'
#used by conda to specify cpus for building packages
export MAKEFLAGS='-j$(nproc)'
#used by conda
export CPU_COUNT='$(nproc)'
# Set image type based on build argument
docker buildx build --builder=docker-container --cache-to=type=s3,region=us-west-2,bucket=cluster-anywhere --cache-from=type=s3,region=us-west-2,bucket=cluster-anywhere --ulimit 'memlock=-1' --ulimit 'nofile=65535:65535' -t jcoffi/cluster-anywhere:$DOCKER_TAG --build-arg IMAGETYPE=$DOCKER_TAG .
