version: '3'
services:
  sut:
    build: .
      args:
        TSAPIKEY: "${TSAPIKEY}"
        TSKEY: "${TSKEY}"
    environment:
      TSAPIKEY: "${TSAPIKEY}"
      TSKEY: "${TSKEY}"
    command: run_tests.sh
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    mem_limit: 5.6gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 41641/udp
    ports:
      - "41641:41641/udp"
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_ADMIN
